language: ruby
rvm:
  - 2.2.4

before_script:
  - psql -U postgres -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:migrate

services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.3"
  apt:
    packages:
      ant
      ant-contrib
      ant-optional
      java-common
      junit4
      openjdk-8-jdk
      openjdk-8-jre
      unzip


  code_climate:
        repo_token: b3db97eb42a4a020fdc687de44194a2a5897c4c3d878ae5fe8bc81239cb52f12
    