language: ruby
rvm:
  - 2.2.4

before_script:
  - psql -U postgres -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml

services:
  - postgresql

addons:
  postgresql: "9.3"